src/api/messages-api.js, src/components/Form/SendMessageForm.jsx
메시지 생성하기 폼 컴포넌트 및 API 연동 추가
메시지를 생성할 수 있는 폼 컴포넌트와 API 연동 로직을 추가하였습니다.
스타일 적용을 위한 css 개발 예정
API 호출 에러 핸들링 코드 작성 예정
=> [Feat] 메시지 생성 폼 컴포넌트 추가

src/components/common/SelectBox.jsx
- SelectBox 공용 컴포넌트 추가
- select, option 태그 기반 공용 컴포넌트 추가
- 전달받는 options에 따라 동적으로 option tag 생성
=> [Feat] SelectBox 공용 컴포넌트 추가

src/components/Form/SendMessageForm.jsx
- SendMessageForm 컴포넌트에서 공용 컴포넌트 사용하도록 변경
- common 패키지에 추가한 공용 컴포넌트 사용하도록 변경
=> [Refactor] 메시지 전송 컴포넌트에서 공용 컴포넌트 사용하도록 변경

package-lock.json, package.json, src/components/Form/SendMessageForm.jsx, src/styles/Form/CKEditor.module.css, src/styles/Form/SendMessageForm.module.css, src/styles/Form/TextEditor.jsx
- 메시지 생성 컴포넌트 스타일 적용 및 텍스트 에디터 구현
- 메시지 생성 컴포넌트인 SendMessageForm 에 스타일 적용
- CKEditor 기반으로 텍스트 에디터 기능 구현
=> [Style] 메시지 생성 컴포넌트 스타일 적용 및 텍스트 에디터 구현

src/pages/RollingPaperPage.jsx
구성
- RollingPaperForm를 import 하여 화면 출력
=> feat: 롤링페이퍼 페이지

src/components/Form/RollingPaperForm.jsx, src/pages/RollingPaperPage.jsx
- 'To.' Input 컴포넌트에 값을 입력하지 않고 focus out 하면, Input 컴포넌트를 에러 상태로 변경하고 “값을 입력해 주세요.” 에러 메세지가 보임.
- '컬러'를 클릭하면 배경색을 선택할 수 있습니다(기본값은 첫번째 항목).
- '생성하기' 버튼은 비활성화 상태에 있다가 받는 사람 이름에 값이 있는 경우 활성화 됩니다.
- '생성하기 버튼을 누르면 /post/{id} 로 이동합니다.
=> Feat: 롤링페이지 만들기 폼 작성

src/components/common/Button.jsx, src/styles/Button.css
- 공용 버튼 컴포넌트 disabled 속성 및 스타일 추가
- 공용 버튼 컴포넌트 disabled 속성 추가
- 공용 버튼 컴포넌트 크기 수정
- disabled 상태일 때 스타일 배경색 변경
=> [Style] 공용 버튼 disabled 속성 및 스타일 추가

src/pages/SendMessagePage.jsx, src/styles/Form/SendMessageForm.module.css, src/styles/Form/TextEditor.jsx, src/styles/Pages/SendMessagePage.module.css
- 메시지 전송 페이지 및 에디터 스타일 적용
- 메시지 전송 페이지 스타일 적용
- 에디터 컴포넌트 스타일 적용
=> [Style] 메시지 전송 페이지 및 에디터 스타일 적용

src/components/Form/SendMessageForm.jsx
- 메시지 전송 폼 유효성 검사 추가
- 메시지 전송 폼 입력 값에 대한 유효성 검사 로직 추가
- 메시지 생성 성공하면 메시지 목록 페이지로 이동하는 기능 추가
=> [Feat] 메시지 전송 폼 유효성 검사 추가

src/styles/Form/SendMessageForm.module.css, src/styles/Pages/SendMessagePage.module.css
- 메시지 생성 폼 반응형 스타일 추가
- 메시지 생성 폼 반응형 스타일 추가
=> [Design] 메시지 생성 폼 반응형 스타일 추가

src/components/Form/ProfileImages.jsx, src/components/Form/SendMessageForm.jsx, src/styles/Form/SendMessageForm.module.css, src/styles/Pages/SendMessagePage.module.css
- 프로필 이미지 컴포넌트 추가
- 프로필 이미지를 선택하여 보여주는 컴포넌트 추가
=> [Feat] 프로필 이미지 컴포넌트 추가

src/components/common/Header.jsx, src/pages/HomePage.jsx, src/styles/Header.css, src/styles/Homepage.css
- 메인 페이지 및 헤더 페이지에 사용되는 공통 버튼 스타일 수정
- 크기 조절이 가능한 container 추가
=> [Design] 공통 버튼 스타일 수정

src/api/list-api.js, src/pages/ListPage.jsx
- list 페이지의 카드 클릭 시, id가 매칭되는 post 페이지로 이동하는 기능 추가
- ListPage.jsx에 링크 이동 기능 추가
- list-api.js에 디버깅 관련 코드 추가
- 디버깅으로 인한 console.log 다수 존재 (추후 삭제 예정)
=> [Feat] 카드 클릭시 id가 매칭되는 post 페이지로 이동

src/api/list-api.js, src/pages/ListPage.jsx, src/styles/Pages/ListPage.module.css
- 최근에 생성된 롤링페이퍼 ui 추가
- 최근에 생성된 롤링페이퍼 카드을 id값 기준 내림차순으로 정렬
- css 작업 완료
- 없음
=> [Feat] 최근에 생성된 롤링페이퍼 ui 추가

src/api/list-api.js, src/pages/ListPage.jsx, src/styles/Button.css, src/styles/Pages/ListPage.module.css
- list 페이지에 공통 컴포넌트 추가
- 헤더 컴포넌트 추가
- Primary 버튼 컴포넌트 추가
- Button.css 파일에 cursor: pointer; 코드 추가
- 없음
=> [Feat] list 페이지에 공통 컴포넌트 추가

package-lock.json, src/pages/HomePage.jsx, src/styles/Homepage.css
main 페이지 반응형 전체 반영 css수정
main페이지 태블릿형에 전체 페이지 vw > 100% 수정/ 여백 정상 적용
main페이지 태블릿형 버튼 위아래 여백 추가
main페이지 모바일 이미지 크기 수정
전체 css 모듈형으로 수정예정
=> [Feat] 반응형 레이아웃 수정

package-lock.json, package.json, src/api/rollingpaper-api.js, src/components/Form/RollingPaperForm.jsx
이미지로 생성하는 부분 - 서버에서 이미지 인식을 못할 시 컬러로 배경을 대체하는 방식을 임시로 넣었습니다.
아직 이미지로 생성하는 부분에서 400 에러가 발생하는 원인을 정확히 모르겠습니다.
(400에러에 관한 원인을 다 고쳤다고 생각해서 어떤 문제가 남은지 모르겠습니다.)
=> [Feat] 이미지로 생성

src/api/list-api.js, src/pages/ListPage.jsx, src/styles/Pages/ListPage.module.css
- 더미 데이터 삭제 후 실제 API 호출
- list-api.js 파일의 더미 데이터 삭제
- 실제 API 연동 및 호출
- 이모지 기능 확인 필요
=> [Fix] 실제 API 호출 및 반영

src/components/Layout/post-components/ShareMenu.jsx
- 카카오톡 공유하기 cleanup 수정
- useEffect 리턴 시 함수로 감싸서 리턴하도록 수정
=> [Fix] 클린업 함수 수정

src/styles/Layout/RollingPaper.module.css
=> [Fix]: 크기 값 수정

src/pages/EditPage.jsx, src/styles/EditPage.module.css
배경화면이 사진인 메세지 수정시 배경이 사진으로 적용될 수 있게
전체적으로 업데이트 되지 않은 postpage의 업데이트 내용 edit 페이지에 적용
배경이 사진인 경우에 edit 페이지로 넘어올때 적용되지 않던 문제 수정
롤링페이지 삭제하기 버튼 위치 수정
롤링페이지 삭제하기 버튼 반응형 추가
const navigate = useNavigate(); 추가
모달에서 롤링페이퍼 삭제버튼이 보이던 현상 수정
=> [Feature] 배경이 사진인 메세지 배경 적용, 롤링페이지 삭제 버튼 반응형 적용

src/pages/ListPage.jsx, src/styles/Pages/ListPage.module.css
- list 페이지 이모지 노출 오류 해결
- ListPage.jsx 이모지 관련 코드 수정
- 관련 css 코드 수정
- 없음
=> [Fix] list 페이지 이모지 노출 오류 해결

src/App.jsx, src/components/common/ErrorBoundary.jsx, src/pages/ErrorPage.jsx
=> [Feat] 에러 바운더리 추가

src/components/Form/RollingPaperForm.jsx
사용자가 입력 값을 쓰면 즉시 error message가 사라지도록 유효성 검사를 추가
=> [Feat]: error message 유효성 검사 수정

src/styles/Button.module.css, src/styles/HomePage.module.css, src/styles/Layout/PostHeader.module.css, src/styles/Layout/RollingPaper.module.css, src/styles/Pages/ListPage.module.css
- 전체적인 페이지 둘러보면서 디테일한 css 수정
- 전체적인 페이지 둘러보면서 디테일한 css 수정
- 없음
=> [Design] 전체적인 페이지 css 디테일 수정

src/api/list-api.js, src/pages/ListPage.jsx
- recipients 정렬 호출 추가
- recipients 정렬 호출 추가
=> [Fix] recipients 정렬 호출 추가

src/styles/HomePage.module.css
메인페이지 이미지 모바일크기 반응형 적용
메인페이지 이미지 모바일크기 반응형 적용
모바일 및 태블릿 크기에서 여백 조정
없음
=> [Design] 메인페이지 이미지 모바일크기 반응형 적용
